#!/usr/bin/env python3
############################################################################
# tools/mkbuildinfo.py
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.  The
# ASF licenses this file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.
#
############################################################################

"""Generate GNU assembly producing .note.nuttx.buildinfo ELF note section.

Consumes (KEY, PATH) pairs passed on the command line via --entries.
PATH is an absolute path to the payload file embedded via .incbin.

Writes a .S file that, when linked into the final ELF, produces one SHT_NOTE
section (no SHF_ALLOC) containing one ELF gABI note per input entry.
"""

import argparse
import sys

# 0x100 avoids readelf -n displaying the type as NT_VERSION (1) / NT_ARCH (2).
NUTTX_NOTE_TYPE = 0x100


def _sanitize_comment(s):
    """Remove '*/' to prevent C-comment premature termination."""
    return s.replace("*/", "*_/")


def _escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def emit_header(out):
    out.write("/* Auto-generated by tools/mkbuildinfo.py — do not edit */\n")
    out.write('.section .note.nuttx.buildinfo, "", %note\n')
    out.write(".balign 4\n\n")


def emit_entry(out, idx, key, path):
    out.write(f"/* entry {idx}: key={_sanitize_comment(key)} */\n")
    out.write(f".long name_end_{idx} - name_start_{idx}\n")
    out.write(f".long desc_end_{idx} - desc_start_{idx}\n")
    out.write(f".long {NUTTX_NOTE_TYPE:#x}\n")
    out.write(f'name_start_{idx}: .asciz "{_escape(key)}"\n')
    out.write(f"name_end_{idx}:   .balign 4\n")
    out.write(f'desc_start_{idx}: .incbin "{_escape(path)}"\n')
    out.write(f"desc_end_{idx}:   .balign 4\n\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--entries", nargs="+", required=True, help="KEY PATH pairs, repeated"
    )
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    flat = args.entries
    if len(flat) % 2:
        sys.exit("mkbuildinfo.py: --entries must be KEY PATH pairs")

    seen = {}
    with open(args.output, "w") as out:
        emit_header(out)
        for i in range(0, len(flat), 2):
            key, path = flat[i], flat[i + 1]
            idx = i // 2
            if key in seen:
                sys.exit(
                    f"mkbuildinfo.py: entry {idx} duplicate key {key!r} "
                    f"(first seen at entry {seen[key]})"
                )
            seen[key] = idx
            emit_entry(out, idx, key, path)


if __name__ == "__main__":
    main()
